# docker-compose.yml
version: '3.8'

services:
  ml-service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
      - MODEL_PATH=/app/models/trained
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s